#! /bin/sh
##############################################################################
# If not stated otherwise in this file or this component's LICENSE file the
# following copyright and licenses apply:
#
# Copyright 2020 RDK Management
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##############################################################################

. /etc/include.properties

MODULE_NAME=$1
echo $MODULE_NAME

loop=1
while [ $loop -eq 1 ]
do
    if [ -f $RAMDISK_PATH/.IarmBusMngrFlag ]; then
          loop=0
          echo "IARM is up, ready to start $MODULE_NAME"
          #rm -rf $RAMDISK_PATH/.IarmBusMngrFlag
    else
         sleep 1
         echo "$MODULE_NAME waiting for IARM manager binaries..!"
    fi
done
exit 0
