#!/bin/sh
# ============================================================================
# RDK MANAGEMENT, LLC CONFIDENTIAL AND PROPRIETARY
# ============================================================================
# This file (and its contents) are the intellectual property of RDK Management, LLC.
# It may not be used, copied, distributed or otherwise  disclosed in whole or in
# part without the express written permission of RDK Management, LLC.
# ============================================================================
# Copyright (c) 2016 RDK Management, LLC. All rights reserved.
# ============================================================================
if [ "$WHITEBOX_ENABLED" == "true" ]; then
     . /etc/wbdevice.conf
else
     wbpath=/opt/www/whitebox
fi
. /etc/authService.conf

if [ -f $aspath/deviceid.dat ]; then
     exit 0
elif [ -f $wbpath/wbdevice.dat ]; then
     exit 0
else
     exit 1
fi
