#! /bin/sh
# ============================================================================
# RDK MANAGEMENT, LLC CONFIDENTIAL AND PROPRIETARY
# ============================================================================
# This file (and its contents) are the intellectual property of RDK Management, LLC.
# It may not be used, copied, distributed or otherwise  disclosed in whole or in
# part without the express written permission of RDK Management, LLC.
# ============================================================================
# Copyright (c) 2016 RDK Management, LLC. All rights reserved.
# ============================================================================
. /etc/include.properties

MODULE=$1
LOG_PIPE=$2
UTILITY_SCRIPT=$3

# Checking the dependency module before startup
nice sh $RDK_PATH/iarm-dependency-checker $MODULE
    
sh $RDK_PATH/$UTILITY_SCRIPT >> $LOG_PIPE &
    
exit 0

