#!/bin/sh
##############################################################################
# If not stated otherwise in this file or this component's LICENSE file the
# following copyright and licenses apply:
#
# Copyright 2020 RDK Management
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##############################################################################

rm -rf  *.* DSG-Package* OCAP_LSV settings data dsg_dir env mnt/* opt r* persistent lib/modules etc usr/local
tar zxf .prev.tgz
if [ $? -ne 0 ]; then
   echo "Unable to revert back to previous version"
   exit -1
fi
sync
echo "Reverted back to previous version.. rebooting now\n"
mv .prev.tgz .curr.tgz
sync
#reboot
/rebootNow.sh -s UpgradeReboot_restore -o "Rebooting the box after reverting back to previous version..."
exit 0

