#!/bin/sh
# ============================================================================
# RDK MANAGEMENT, LLC CONFIDENTIAL AND PROPRIETARY
# ============================================================================
# This file (and its contents) are the intellectual property of RDK Management, LLC.
# It may not be used, copied, distributed or otherwise  disclosed in whole or in
# part without the express written permission of RDK Management, LLC.
# ============================================================================
# Copyright (c) 2016 RDK Management, LLC. All rights reserved.
# ============================================================================
rm -rf  *.* DSG-Package* OCAP_LSV settings data dsg_dir env mnt/* opt r* persistent lib/modules etc usr/local
tar zxf .prev.tgz
if [ $? -ne 0 ]; then
   echo "Unable to revert back to previous version"
   exit -1
fi
sync
echo "Reverted back to previous version.. rebooting now\n"
mv .prev.tgz .curr.tgz
sync
#reboot
/rebootNow.sh -s UpgradeReboot_restore -o "Rebooting the box after reverting back to previous version..."
exit 0

