#!/bin/sh
# ============================================================================
# RDK MANAGEMENT, LLC CONFIDENTIAL AND PROPRIETARY
# ============================================================================
# This file (and its contents) are the intellectual property of RDK Management, LLC.
# It may not be used, copied, distributed or otherwise  disclosed in whole or in
# part without the express written permission of RDK Management, LLC.
# ============================================================================
# Copyright (c) 2016 RDK Management, LLC. All rights reserved.
# ============================================================================
. /etc/include.properties

trap "" 13

touch /tmp/ri-recovery-flag2
if [ -f $RDK_PATH/gzEnabled.sh ]; then
     sh $RDK_PATH/gzEnabled.sh & 
fi

cd /mnt/nfs/env
# Dump the version.txt
cat /version.txt

echo "`/bin/timestamp` -------Following image version is coming up -----"

if [ ! -f $PERSISTENT_PATH/.lightsleepKillSwitchEnable ]
then
     export SYSRESLOG_PATH=$TEMP_LOG_PATH
fi

./runri.sh
