#!/bin/sh
# ============================================================================
# RDK MANAGEMENT, LLC CONFIDENTIAL AND PROPRIETARY
# ============================================================================
# This file (and its contents) are the intellectual property of RDK Management, LLC.
# It may not be used, copied, distributed or otherwise  disclosed in whole or in
# part without the express written permission of RDK Management, LLC.
# ============================================================================
# Copyright (c) 2016 RDK Management, LLC. All rights reserved.
# ============================================================================
if [ -f /lib/rdk/utils.sh ];then
     . /lib/rdk/utils.sh
fi

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib:/usr/lib:/lib

#Path of tr69hostif binaries and files                           
TR69HOSTIF_BIN_PATH=/usr/bin

PID=`ps aux | grep tr69hostif | grep -v grep | awk '{print $2}'`                                               

if [ "$PID" != "" ]; then
  kill -9 $PID
  sleep 1
fi

echo "$0: Starting tr69hostif ..."

sleep 40
                                                                                                                               
#start the tr69hostif CPE client                                                                                 
if [ -f $TR69HOSTIF_BIN_PATH/tr69hostif ]; then                                                                  
   until $TR69HOSTIF_BIN_PATH/tr69hostif -c /etc/tr69/mgrlist.conf
   do
     echo "$0: Go to the restart..."
   done
fi
