#!/bin/sh
##############################################################################
# If not stated otherwise in this file or this component's LICENSE file the
# following copyright and licenses apply:
#
# Copyright 2020 RDK Management
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##############################################################################

if [ -f /lib/rdk/utils.sh ];then
     . /lib/rdk/utils.sh
fi

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib:/usr/lib:/lib

#Path of tr69hostif binaries and files                           
TR69HOSTIF_BIN_PATH=/usr/bin

PID=`ps aux | grep tr69hostif | grep -v grep | awk '{print $2}'`                                               

if [ "$PID" != "" ]; then
  kill -9 $PID
  sleep 1
fi

echo "$0: Starting tr69hostif ..."

sleep 40
                                                                                                                               
#start the tr69hostif CPE client                                                                                 
if [ -f $TR69HOSTIF_BIN_PATH/tr69hostif ]; then                                                                  
   until $TR69HOSTIF_BIN_PATH/tr69hostif -c /etc/tr69/mgrlist.conf
   do
     echo "$0: Go to the restart..."
   done
fi
