#!/bin/sh
# ============================================================================
# RDK MANAGEMENT, LLC CONFIDENTIAL AND PROPRIETARY
# ============================================================================
# This file (and its contents) are the intellectual property of RDK Management, LLC.
# It may not be used, copied, distributed or otherwise  disclosed in whole or in
# part without the express written permission of RDK Management, LLC.
# ============================================================================
# Copyright (c) 2016 RDK Management, LLC. All rights reserved.
# ============================================================================
OPTS=""

if [ -n "$D" ]; then
    OPTS="--root=$D"
fi

if type systemctl >/dev/null 2>/dev/null; then
	if [ -z "$D" ]; then
		systemctl stop hosts.service dcm-log.service previous-log-backup.service swupdate.service ip-setup-monitor.service dump-log.timer logrotate.timer mocastatuslogger.timer scheduled-reboot.service dump-backup.service
	fi

	systemctl $OPTS disable hosts.service dcm-log.service previous-log-backup.service swupdate.service ip-setup-monitor.service dump-log.timer logrotate.timer mocastatuslogger.timer scheduled-reboot.service dump-backup.service
fi
