#!/bin/sh
# ============================================================================
# RDK MANAGEMENT, LLC CONFIDENTIAL AND PROPRIETARY
# ============================================================================
# This file (and its contents) are the intellectual property of RDK Management, LLC.
# It may not be used, copied, distributed or otherwise  disclosed in whole or in
# part without the express written permission of RDK Management, LLC.
# ============================================================================
# Copyright (c) 2016 RDK Management, LLC. All rights reserved.
# ============================================================================
### BEGIN INIT INFO
# Provides: dbus-service
# Required-Start:    
# Required-Stop:
# Should-Stop:
# Default-Start:     3
# Default-Stop:
# Short-Description: 
### END INIT INFO
. /lib/rdk/init-functions

# Defaults can be overridden in this file
INIT_SCRIPT_DEFAULTS_FILE="/etc/include.properties"

# Load alternate configuration if exists
if [ -f $INIT_SCRIPT_DEFAULTS_FILE ]; then
     . $INIT_SCRIPT_DEFAULTS_FILE
fi

# Defaults
INIT_SCRIPT_NAME="DBUS-SERVICE"                    # full path to the executable
INIT_SCRIPT_EXECUTABLE=""                          # options to pass to the executable 
INIT_SCRIPT_OPTIONS=""                             # a decriptive name 
INIT_SCRIPT_HOMEDIR="/"                            # place where to cd before running
INIT_SCRIPT_PIDFILE=""                             # pid file name
INIT_SCRIPT_LOGFILE="system.log"                   # log file name 
INIT_SLEEPTIME=""

export PATH=$PATH:/usr/local/bin:/usr/bin:/bin:/sbin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/bin:/lib:/usr/lib:/usr/local/lib:/mnt/nfs/bin

start_function() {
    pre_start "$INIT_SCRIPT_LOGFILE" ">>"
    if [ -f /lib/rdk/dbus-starter ];then
        sh /lib/rdk/dbus-starter
    else 
        mkdir -p /var/run/dbus
        mkdir -p /tmp/run/dbus
        rm -f /var/run/dbus/pid
        /usr/local/bin/dbus-daemon  --config-file=/etc/dbus-1/system.conf
    fi
    post_start $?
}

stop_function() {
    pre_stop
    killall dbus-daemon 
    post_stop 0
}
 
case "$1" in
  start)
    start_function
    ;;
  stop)
    stop_function
    ;;
  restart)
    $0 stop && $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
  ;;
esac
