#!/bin/sh
# ============================================================================
# RDK MANAGEMENT, LLC CONFIDENTIAL AND PROPRIETARY
# ============================================================================
# This file (and its contents) are the intellectual property of RDK Management, LLC.
# It may not be used, copied, distributed or otherwise  disclosed in whole or in
# part without the express written permission of RDK Management, LLC.
# ============================================================================
# Copyright (c) 2016 RDK Management, LLC. All rights reserved.
# ============================================================================

### BEGIN INIT INFO
# Provides:          dcm-log-service
# Should-Start:
# Required-Start:    dropbear-service
# Required-Stop:
# Default-Start:     3
# Default-Stop:
# Short-Description: 
### END INIT INFO
. /lib/rdk/init-functions

# Defaults can be overridden in this file
INIT_SCRIPT_DEFAULTS_FILE="/etc/include.properties"

# Load alternate configuration if exists
if [ -f $INIT_SCRIPT_DEFAULTS_FILE ]; then
     . $INIT_SCRIPT_DEFAULTS_FILE
fi

# Defaults
INIT_SCRIPT_NAME="DCM-LOG-BACKUP"              # full path to the executable
INIT_SCRIPT_EXECUTABLE=""                      # options to pass to the executable 
INIT_SCRIPT_OPTIONS=""                         # a decriptive name 
INIT_SCRIPT_HOMEDIR="/"                        # place where to cd before running
INIT_SCRIPT_PIDFILE=""                         # pid file name
INIT_SCRIPT_LOGFILE="applications.log"         # log file name 
INIT_SLEEPTIME=""                              # how long to wait for startup and shutdown

. /etc/device.properties

if [ "$BUILD_TYPE" != "prod" ] && [ -f /opt/dcm.properties ]; then
      . /opt/dcm.properties
else
      . /etc/dcm.properties
fi

start_function() {
    pre_start "$INIT_SCRIPT_LOGFILE" ">>"
    # Set the tftp server                                                                 
    if [ "$BUILD_TYPE" = "prod" ]; then                             
          TFTP_SERVER="logs.xcal.tv"                                                 
    else                                                           
          TFTP_SERVER=$LOG_SERVER                                       
    fi 
    if [ "$BUILD_TYPE" != "prod" ]; then
        if [ -f $PERSISTENT_PATH/logger.conf ] ; then
            TFTP_SERVER=`grep -v '^[[:space:]]*#' $PERSISTENT_PATH/logger.conf`
        fi
    fi
    echo "$RDK_PATH/StartDCM.sh $DCM_LOG_SERVER $DCM_LOG_SERVER_URL $TFTP_SERVER 0 $DCM_SCP_SERVER"    
    $RDK_PATH/StartDCM.sh $DCM_LOG_SERVER $DCM_LOG_SERVER_URL $TFTP_SERVER 0 $DCM_SCP_SERVER &
    post_start $?
}

stop_function() {
    pre_stop
    sh /lib/rdk/processPID.sh /lib/rdk/StartDCM.sh | xargs kill -9 
    sh /lib/rdk/processPID.sh /lib/rdk/DCMscript.sh | xargs kill -9
    sh /lib/rdk/processPID.sh /lib/rdk/uploadSTBLogs.sh | xargs kill -9
    post_stop 0
}
 
case "$1" in
  start)
    start_function
    ;;
  stop)
    stop_function
    ;;
  restart)
    $0 stop && $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
  ;;
esac

