#!/bin/busybox sh
##############################################################################
# If not stated otherwise in this file or this component's LICENSE file the
# following copyright and licenses apply:
#
# Copyright 2020 RDK Management
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##############################################################################

### BEGIN INIT INFO
# Provides: iptables_init
# Required-Start:
# Should-Start:
# Required-Stop:
# Should-Stop:
# Default-Start:     3
# Default-Stop:
# Short-Description: 
### END INIT INFO

SCRIPTNAME=`basename $0`
PATH=/usr/local/bin:/usr/bin:/bin:/sbin

. /etc/init.d/init_utilities
. /lib/rdk/init-functions

INIT_SCRIPT_NAME="IPTABLES_INIT"               # full path to the executable
INIT_SCRIPT_EXECUTABLE=""                      # options to pass to the executable 
INIT_SCRIPT_OPTIONS=""                         # a decriptive name 
INIT_SCRIPT_HOMEDIR="/"                        # place where to cd before running
INIT_SCRIPT_PIDFILE=""                         # pid file name
INIT_SCRIPT_LOGFILE="system.log"               # log file name 
INIT_SLEEPTIME=""                              # how long to wait for startup and shutdown
#
# Set this variable to 1 to enable debug by way of the DEBUG function below.
#
_DEBUG=0

#
# "DEBUG" echoes a line of debug information to a log file if _DEBUG equals 1.
#
DEBUG()
{
   # Save the current exit status and return it afterwards. This is to stop the
   # "${_DEBUG} -eq 1" test from propagating a false error if debug isn't enabled.
   local SAVE_EXIT_STATUS=$?

   [ ${_DEBUG} -eq 1 ] && ( echo $@ >>/var/run/${SCRIPTNAME}_debug )

   return $SAVE_EXIT_STATUS
}

start_function()
{
   pre_start "$INIT_SCRIPT_LOGFILE" ">>"

   # device specific iptable rules
   if [ -f /etc/iptables_rules.sh ];then
        sh /etc/iptables_rules.sh
   fi
   # generic RDK iptables rule
   if [ -f /lib/rdk/iptables_init ] ;then
       sh /lib/rdk/iptables_init &
   else
      echo "The script /lib/rdk/iptables_init not found - not applying iptables rules"
   fi

   post_start $?
}

stop_function()
{
   echo "${SCRIPTNAME}: Stopping - nothing to do."
}

case $1 in
    "start")
        pre_start "system.log" ">>"
        start_function
        post_start $?
        ;;
    "stop")
        pre_stop
        stop_function
        post_stop $?
        ;;
    "restart")
        stop_function
        start_function
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        ;;
esac
