#!/bin/sh
##############################################################################
# If not stated otherwise in this file or this component's LICENSE file the
# following copyright and licenses apply:
#
# Copyright 2020 RDK Management
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##############################################################################


### BEGIN INIT INFO
# Provides: lightsleep-service
# Required-Start:
# Should-Start: network disk_check lighttpd 
# Required-Stop:
# Should-Stop:
# Default-Start:     3
# Default-Stop:
# Short-Description: 
### END INIT INFO

SCRIPTNAME=`basename $0`
export PATH=$PATH:/usr/bin:/bin:/usr/local/bin:/sbin:/usr/local/sbin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/lib:/usr/local/lib
PATH=/usr/local/bin:/usr/bin:/bin:/sbin

. /etc/include.properties
. /lib/rdk/init-functions

start_function() {
      # Cleaning the older disable flag
      sh $RDK_PATH/lightsleep_utility.sh &  
}

stop_function() {
   echo stopping lightsleep 
   killall lightsleep
}

case $1 in
    "start")
        pre_start "lightsleep.log" ">>"
        start_function
        post_start $?
        ;;
    "stop")
        pre_stop
        stop_function
        post_stop $?
        ;;
    "restart")
        stop_function
        start_function
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        ;;
esac
