#!/bin/sh
##############################################################################
# If not stated otherwise in this file or this component's LICENSE file the
# following copyright and licenses apply:
#
# Copyright 2020 RDK Management
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##############################################################################


### BEGIN INIT INFO
# Provides: lighttpd
# Required-Start: 
# Should-Start: previous-log-backup 
# Required-Stop: 
# Default-Start:     3
# Default-Stop:
# Short-Description: 
### END INIT INFO
. /lib/rdk/init-functions

# Defaults can be overridden in this file
INIT_SCRIPT_DEFAULTS_FILE="/etc/include.properties"

# Load alternate configuration if exists
if [ -f $INIT_SCRIPT_DEFAULTS_FILE ]; then
     . $INIT_SCRIPT_DEFAULTS_FILE
fi

# Defaults
INIT_SCRIPT_NAME="HTTP-SERVICE"                     # full path to the executable
INIT_SCRIPT_EXECUTABLE=""                           # options to pass to the executable 
INIT_SCRIPT_OPTIONS=""                              # a decriptive name 
INIT_SCRIPT_HOMEDIR="/"                             # place where to cd before running
INIT_SCRIPT_PIDFILE=""                              # pid file name
INIT_SCRIPT_LOGFILE="applications.log"              # log file name 
INIT_SLEEPTIME=""                                   # how long to wait for startup and shutdown
 
export PATH=$PATH:/usr/bin:/bin:/usr/local/bin:/sbin:/usr/local/lighttpd/sbin:/usr/local/sbin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/Qt/lib:/usr/local/lib

LOGFILE=$LOG_PATH/lighttpd.log 

. /etc/device.properties

wait_for_default_ecm_ip() {
    loop=1
    while [ "$loop" -eq 1 ]
    do
        if [ "$DEFAULT_ECM_IP" ]; then
              ret=`ifconfig "$DEFAULT_ECM_INTERFACE" | grep "$DEFAULT_ECM_IP"`
        else
              ret=`ifconfig | grep "$DEFAULT_ECM_INTERFACE" | grep -v "$DEFAULT_ECM_INTERFACE:"`
        fi
        if [ ! "$ret" ]; then
            echo "--------- waiting for default ECM interface to be up ---------" >> $LOGFILE
            ifconfig "$DEFAULT_ECM_INTERFACE" "$DEFAULT_ECM_IP" up
            sleep 1
        else
            loop=0
        fi
    done
    return 0
}

start_function() {
        if [ "$DEVICE_TYPE" != "mediaclient" ]; then
              if [  -n "$DEFAULT_ECM_INTERFACE" ]; then
                    wait_for_default_ecm_ip
              fi
        fi
        pre_start "$INIT_SCRIPT_LOGFILE" ">>"
        sh $RDK_PATH/getDeviceDetails.sh &
        sh $RDK_PATH/lighttpd_utility.sh &
	post_start $?
}

stop_function() {
        pre_stop   
        # Can't call authservice.sh after killall, since it kills that script as well
        if [ -x /etc/authservice.sh ]; then
            /etc/authservice.sh stop
        fi     
        killall -9 lighttpd
        post_stop $?
} 

case "$1" in
  start)
    start_function
    ;;
  stop)
    stop_function
    ;;
  restart)
    $0 stop && $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
  ;;
esac

