#!/bin/sh
# ============================================================================
# RDK MANAGEMENT, LLC CONFIDENTIAL AND PROPRIETARY
# ============================================================================
# This file (and its contents) are the intellectual property of RDK Management, LLC.
# It may not be used, copied, distributed or otherwise  disclosed in whole or in
# part without the express written permission of RDK Management, LLC.
# ============================================================================
# Copyright (c) 2016 RDK Management, LLC. All rights reserved.
# ============================================================================

### BEGIN INIT INFO
# Provides:          mfrlib-service 
# Required-Start:
# Required-Stop:
# Should-Stop:
# Default-Start:     3
# Default-Stop:
# Short-Description: 
### END INIT INFO
. /lib/rdk/init-functions

# Defaults can be overridden in this file
INIT_SCRIPT_DEFAULTS_FILE="/etc/include.properties"

# Load alternate configuration if exists
if [ -f $INIT_SCRIPT_DEFAULTS_FILE ]; then
     . $INIT_SCRIPT_DEFAULTS_FILE
fi

# Defaults
INIT_SCRIPT_NAME="MFRLIB"                      # full path to the executable
INIT_SCRIPT_EXECUTABLE=""                      # options to pass to the executable 
INIT_SCRIPT_OPTIONS=""                         # a decriptive name 
INIT_SCRIPT_HOMEDIR="/"                        # place where to cd before running
INIT_SCRIPT_PIDFILE=""                         # pid file name
INIT_SCRIPT_LOGFILE="system.log"               # log file name 
INIT_SLEEPTIME=""                              # how long to wait for startup and shutdown

. /etc/env_setup.sh
. /etc/device.properties

MFRLIB_LOG="$LOG_PATH/mfrlib_log.txt"
if [ "$LIGHTSLEEP_ENABLE" = "true" ]; then
     MFRLIB_PIPE="$TEMP_LOG_PATH/pipe_mfrlib_log"
     count1=`find $TEMP_LOG_PATH -name pipe_mfrlib_log -type f`
     if [ "$count1" != "" ]; then
          cat $MFRLIB_PIPE >> $MFRLIB_LOG
          echo "$MFRLIB_PIPE is not a pipe" >> $LOG_PATH/lightsleep.log
          rm -rf $MFRLIB_PIPE
     fi

     mkfifo $MFRLIB_PIPE &> /dev/null
    # Checking the logging pipe before startup
    value=`ps | grep $MFRLIB_PIPE | grep -v grep`
    if [ "$value" = "" ]; then
         cat $MFRLIB_PIPE >> $MFRLIB_LOG &
    fi

    value=`ps | grep $MFRLIB_PIPE | grep -v grep`
    if [ "$value" = "" ]; then
         cat $MFRLIB_PIPE >> $MFR_LOG &
    fi
else
     MFRLIB_PIPE=$MFRLIB_LOG
fi


start_function() {
    pre_start "$INIT_SCRIPT_LOGFILE" ">>"
    if [ -f /lib/rdk/mfr-launcher ];then
         sh /lib/rdk/mfr-launcher $MFRLIB_PIPE
    fi
    post_start $?
}

stop_function() {
    pre_stop
    ret=`killall -9 MfrLibApp`
    post_stop $ret
}
 
case "$1" in
  start)
    start_function
    ;;
  stop)
    stop_function
    ;;
  restart)
    $0 stop && $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
  ;;
esac
