#!/bin/sh
##############################################################################
# If not stated otherwise in this file or this component's LICENSE file the
# following copyright and licenses apply:
#
# Copyright 2020 RDK Management
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##############################################################################


### BEGIN INIT INFO
# Provides: portmap-service
# Required-Start:
# Should-Start:  opt-backup-setup
# Required-Stop:
# Default-Start:     3
# Default-Stop:
# Short-Description: 
### END INIT INFO

SCRIPTNAME=`basename $0` 

. /lib/rdk/init-functions

# Defaults can be overridden in this file
INIT_SCRIPT_DEFAULTS_FILE="/etc/include.properties"

# Load alternate configuration if exists
if [ -f $INIT_SCRIPT_DEFAULTS_FILE ]; then
     . $INIT_SCRIPT_DEFAULTS_FILE
fi

# Defaults
INIT_SCRIPT_NAME="POD"                               # full path to the executable
INIT_SCRIPT_EXECUTABLE=""                            # options to pass to the executable 
INIT_SCRIPT_OPTIONS=""                               # a decriptive name 
INIT_SCRIPT_HOMEDIR="/"                              # place where to cd before running
INIT_SCRIPT_PIDFILE=""                               # pid file name
INIT_SCRIPT_LOGFILE="applications.log"               # log file name 
INIT_SLEEPTIME="" 

. /etc/device.properties

export PATH=$PATH:/usr/sbin:/bin

start_function() {
    pre_start "applications.log" ">>"
    # calling the portmap binary
    if [ "$DEVICE_TYPE" = "mediaclient" ];then
         portmap -l &
    else
         portmap &
    fi
    post_start $?
}

stop_function() {
    pre_stop
    killall portmap
    post_stop $?
}

case $1 in
    "start")
        start_function
        ;;
    "stop")
        stop_function
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
     ;;
esac

