#!/bin/sh
# ============================================================================
# RDK MANAGEMENT, LLC CONFIDENTIAL AND PROPRIETARY
# ============================================================================
# This file (and its contents) are the intellectual property of RDK Management, LLC.
# It may not be used, copied, distributed or otherwise  disclosed in whole or in
# part without the express written permission of RDK Management, LLC.
# ============================================================================
# Copyright (c) 2016 RDK Management, LLC. All rights reserved.
# ============================================================================

### BEGIN INIT INFO
# Provides: tftp-service
# Should-Start: dns-service
# Required-Start:    
# Required-Stop:
# Default-Start:     3
# Default-Stop:
# Short-Description: 
### END INIT INFO

. /lib/rdk/init-functions

export PATH=$PATH:/bin

start_function() {
    pre_start
    echo "Starting tftpd service..."
    tftpserver -v &                                            
    post_start $?
}

stop_function() {
    pre_stop
    post_stop 0
}

case $1 in
    start)
        start_function
        ;;
    stop)
        stop_function
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac

