#!/bin/sh
# ============================================================================
# RDK MANAGEMENT, LLC CONFIDENTIAL AND PROPRIETARY
# ============================================================================
# This file (and its contents) are the intellectual property of RDK Management, LLC.
# It may not be used, copied, distributed or otherwise  disclosed in whole or in
# part without the express written permission of RDK Management, LLC.
# ============================================================================
# Copyright (c) 2016 RDK Management, LLC. All rights reserved.
# ============================================================================

### BEGIN INIT INFO
# Provides:          vod-service 
# Should-Start:
# Required-Start:    xre-service 
# Required-Stop:
# Default-Start:     3
# Default-Stop:
# Short-Description: 
### END INIT INFO
. /lib/rdk/init-functions

# Defaults can be overridden in this file
INIT_SCRIPT_DEFAULTS_FILE="/etc/include.properties"

# Load alternate configuration if exists
if [ -f $INIT_SCRIPT_DEFAULTS_FILE ]; then
     . $INIT_SCRIPT_DEFAULTS_FILE
fi

# Defaults
INIT_SCRIPT_NAME="VOD-SERVICE"                       # full path to the executable
INIT_SCRIPT_EXECUTABLE=""                            # options to pass to the executable 
INIT_SCRIPT_OPTIONS=""                               # a decriptive name 
INIT_SCRIPT_HOMEDIR="/"                              # place where to cd before running
INIT_SCRIPT_PIDFILE=""                               # pid file name
INIT_SCRIPT_LOGFILE="applications.log"               # log file name 
INIT_SLEEPTIME=""                                    # how long to wait for startup and shutdown
 
. /etc/device.properties
. /etc/env_setup.sh

LOG_FILE=$LOG_PATH/vodclient_log.txt                                                    
if [ "$LIGHTSLEEP_ENABLE" = "true" ]; then                                                      
     LOG_PIPE="$TEMP_LOG_PATH/pipe_vodclient_log"
     count1=`find $TEMP_LOG_PATH -name pipe_vodclient_log -type f`
     if [ "$count1" != "" ]; then
            cat $LOG_PIPE >> $LOG_FILE
            echo "$LOG_PIPE is not a pipe" >> $LOG_PATH/lightsleep.log
            rm -rf $LOG_PIPE
     fi                                            
     mkfifo $LOG_PIPE &> /dev/null
     # Checking the logging path before startup                                           
     value=`ps | grep $LOG_PIPE | grep -v grep`                                       
     if [ "$value" = "" ]; then                                                           
           cat $LOG_PIPE >> $LOG_FILE &                                                    
     fi 
else                                                                                  
     LOG_PIPE=$LOG_FILE
fi

start_function() {
    pre_start "$INIT_SCRIPT_LOGFILE" ">>"
    # Creating the log backup folders
    #------------ start VOD -----------------
    sh $RDK_PATH/runVodClientApp >> $LOG_PIPE 2>&1 &
    post_start $?
}

stop_function() {
    pre_stop
    killall vodClientApp
    if [ "$LIGHTSLEEP_ENABLE" = "true" ]; then
         sh /lib/rdk/processPID.sh "$LOG_PIPE" | xargs kill -9
    fi
    if [ -f /tmp/.vodClient_started ]; then
	 rm -rf /tmp/.vodClient_started
    fi
    post_stop 0
}
 
case "$1" in
  start)
    start_function
    ;;
  stop)
    stop_function
    ;;
  restart)
    $0 stop && $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
  ;;
esac

